[Setup]
AppName=Network Watchdog Service
AppVersion=3.8.0
AppPublisher=Network Watchdog
DefaultDirName={autopf}\NetworkWatchdog
ArchitecturesInstallIn64BitMode=x64
OutputBaseFilename=NetworkWatchdog_Installer
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
SetupLogging=yes
CloseApplications=force

[Files]
; Grab everything generated by the publish commands to prevent missing dependency crashes
Source: "..\out\service\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\out\tray\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autostartup}\Network Watchdog Tray"; Filename: "{app}\NetworkWatchdog.TrayApp.exe"
Name: "{group}\Network Watchdog"; Filename: "{app}\NetworkWatchdog.TrayApp.exe"

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssInstall then
  begin
    Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM NetworkWatchdog.TrayApp.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Exec(ExpandConstant('{sys}\sc.exe'), 'stop NetworkWatchdogService', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Sleep(2000); 
  end;
end;

[Run]
Filename: "{sys}\sc.exe"; Parameters: "create NetworkWatchdogService binPath= ""{app}\NetworkWatchdogService.exe"" start= auto"; Flags: runhidden
Filename: "{sys}\sc.exe"; Parameters: "start NetworkWatchdogService"; Flags: runhidden
Filename: "{app}\NetworkWatchdog.TrayApp.exe"; Description: "Launch NetworkWatchdog Dashboard"; Flags: nowait postinstall runasoriginaluser

[UninstallRun]
Filename: "{sys}\taskkill.exe"; Parameters: "/F /IM NetworkWatchdog.TrayApp.exe"; Flags: runhidden
Filename: "{sys}\sc.exe"; Parameters: "stop NetworkWatchdogService"; Flags: runhidden
Filename: "{sys}\sc.exe"; Parameters: "delete NetworkWatchdogService"; Flags: runhidden